// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXSav_jbXW-QEAr_9BRsznP3ieaPcCoA',
    appId: '1:955080993594:web:c1490e8abefdbf478a7e03',
    messagingSenderId: '955080993594',
    projectId: 'project-universe-7f31a',
    authDomain: 'project-universe-7f31a.firebaseapp.com',
    storageBucket: 'project-universe-7f31a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXsPyw3PAL3k5gmfMxHtadDIF0UKNJG7Q',
    appId: '1:955080993594:android:bfe35582ea5c757d8a7e03',
    messagingSenderId: '955080993594',
    projectId: 'project-universe-7f31a',
    storageBucket: 'project-universe-7f31a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChlK68ZLbC0jojjkT9JrAcrk7ACasHTVM',
    appId: '1:955080993594:ios:4548557662d6a05c8a7e03',
    messagingSenderId: '955080993594',
    projectId: 'project-universe-7f31a',
    storageBucket: 'project-universe-7f31a.appspot.com',
    iosClientId: '955080993594-au6psg9b74p464egnr59suhrkkgpo7q9.apps.googleusercontent.com',
    iosBundleId: 'com.vincentgonnet.projectuniverse.projectUniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChlK68ZLbC0jojjkT9JrAcrk7ACasHTVM',
    appId: '1:955080993594:ios:4548557662d6a05c8a7e03',
    messagingSenderId: '955080993594',
    projectId: 'project-universe-7f31a',
    storageBucket: 'project-universe-7f31a.appspot.com',
    iosClientId: '955080993594-au6psg9b74p464egnr59suhrkkgpo7q9.apps.googleusercontent.com',
    iosBundleId: 'com.vincentgonnet.projectuniverse.projectUniverse',
  );
}
